import React from 'react';
import SEO from '../components/SEO';
import AdSlot from '../components/AdSlot';
import { Link } from 'react-router-dom';
import './Terms.css';

export default function Terms() {
  return (
    <>
      <SEO 
        title="Terms of Service — Speeda Test 360"
        description="Terms of Service for using the Speeda Test 360 free internet speed test diagnostic suite."
        keywords="terms of service, speeda test 360 terms, speed test terms of use, legal terms"
        canonical="/terms"
      />

      <div className="legal-page-container">
        <AdSlot slotId="terms-top-banner" type="banner" />

        <div className="glass-panel legal-card">
          <h1>📜 Terms of Service</h1>
          <p className="effective-date">Last Updated: October 2026</p>

          <p>
            By accessing or using <strong>speedatest360.online</strong> (the "Service"), you acknowledge that you have read, understood, and agreed to be legally bound by these Terms of Service. If you do not agree with any portion of these terms, please discontinue use of the Service immediately.
          </p>

          <section>
            <h2>1. Nature & Scope of the Service</h2>
            <p>
              Speeda Test 360 provides a suite of free web-based broadband and network diagnostic tools, including throughput measurement (download and upload), ping latency, jitter, website performance testing, and IP information lookup. The Service is provided free of charge for informational, diagnostic, and personal evaluation purposes.
            </p>
          </section>

          <section>
            <h2>2. Accuracy & Variable Network Factors</h2>
            <p>
              Speed test measurements generated by Speeda Test 360 represent real-time throughput between your web browser and target edge servers at the precise moment of testing. Connection performance can fluctuate based on variables beyond our control, including Wi-Fi signal quality, router hardware processing, internal network traffic, ISP bandwidth throttling, and global routing peering. Consequently, Speeda Test 360 does not guarantee that results will permanently match contracted ISP speed tiers.
            </p>
          </section>

          <section>
            <h2>3. Acceptable Use Policy</h2>
            <p>You agree to use Speeda Test 360 responsibly and legally. You agree NOT to:</p>
            <ul>
              <li>Deploy automated headless crawlers, stress-testing bots, or scripts designed to overwhelm testing endpoints.</li>
              <li>Attempt to reverse-engineer, decompile, or intercept server infrastructure supporting the Service.</li>
              <li>Misrepresent Speeda Test 360 results for fraudulent commercial claims or deceptive practices.</li>
            </ul>
          </section>

          <section>
            <h2>4. Third-Party Advertising & Links</h2>
            <p>
              The Service is supported by third-party advertising networks, including Google AdSense. Displayed advertisements and outbound hyperlinks are governed by our <Link to="/privacy">Privacy Policy</Link> and the respective third parties' terms. Speeda Test 360 does not endorse third-party products advertised on the platform.
            </p>
          </section>

          <section>
            <h2>5. Intellectual Property Rights</h2>
            <p>
              All proprietary algorithms, user interface designs, logos, graphics, source code, and original editorial content on speedatest360.online are the intellectual property of Speeda Test 360 and are protected under international copyright and intellectual property treaties.
            </p>
          </section>

          <section>
            <h2>6. Disclaimer of Warranties & Limitation of Liability</h2>
            <p>
              THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, SPEEDA TEST 360 DISCLAIMS ALL LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL LOSSES RESULTING FROM THE USE OF OR INABILITY TO USE THE SERVICE.
            </p>
          </section>

          <section>
            <h2>7. Governing Law & Modifications</h2>
            <p>
              Speeda Test 360 reserves the right to modify these Terms of Service at any time. Material revisions will be reflected by the "Last Updated" date at the top of this document. Continued use of the platform after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2>8. Contact & Support</h2>
            <p>
              For legal inquiries, copyright questions, or support regarding these Terms, contact our legal desk at <a className="email" href="mailto:support@speedatest360.online">support@speedatest360.online</a> or submit an inquiry via our <Link to="/contact">Contact Page</Link>.
            </p>
          </section>
        </div>

        <AdSlot slotId="terms-bottom-banner" type="banner" />
      </div>
    </>
  );
}
